sudo: required
services:
  - docker

before_install:
  - docker build -t geomartins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geomartins/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-287119771881"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"